RN101: false
RN50: true
RN50x16: false
RN50x4: false
RN50x64: false
ViTB16: true
ViTB32: true
ViTL14: false
ViTL14_336: true
batch_name: prompt_salad_example
images_out: /home/mike/ai/images_out
prompt_salad: true
prompt_salad_template: a {adjectives} {locations} spanning across a river of {of_something}, art by {progrock/artist}, trending on artstation
width_height:
- 2048
- 512
prompt_salad_amount: 100
n_batches: 1
steps: 250
set_seed: 8675309